### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by a-pasquale** [hackforwesternmass/david-ruggles-center#1]
Content:
https://docs.google.com/document/d/1Ypny1ehCsqAP6rSE6vBvW_KXHP_-n-IxrcF1XDteFfI/edit

Sections can be page anchors on a single page, I think.

- [x] Add content to /about page
- [x] Remove existing single pages
- [x] Update menu to use page anchors

**Comment by jrabbit** [comment]
I cleaned up the menu on the staging website

**Comment by a-pasquale** [comment]
About page is done.
